---
title: 'Chapter Two: Philosophical Foundations of Quantitative methods'
author: "Simona Simona"
date: "4/12/2020"
output: pdf_document
header-includes:
   - \usepackage{setspace}
   - \singlespacing
fontsize: 11pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Where do we start from?

From the outset we must establish that quantitative methods are not an end in themselves but they are means to an end. Meaning that we don't go around standing methods for the sake of methods but we study methods to accomplish an end which in most cases is an answer to a particular research problem that we have. A choise of the methods you use should not be instigated your liking of one particular method versus another. It should instead instigated by the best methods that address the problem as hand.

### The research paradigm

Going back to Archer’s sentiment about the importance of philosophy in social research,
she went on to put it more emphatically in the same article: 'It is unavoidable that each researcher brings their ontology to the investigation of any topic. This can be implicit or explicit, but it is one or the other because all research conceptualizes the social—or any part of it—in a particular way, welcoming certain concepts and ignoring or rejecting others, viewing causality from a specific perspective and presenting the results accordingly' (Archer 2016: 426).

In this study, a research paradigm is defined as the researcher’s worldview. It describes a ’perspective, thinking or school of thought, or a set of shared beliefs, that informs the meanings or interpretations of research data (Kivunja and Kuyini, 2017: 26). Like Archer has indicated, the research paradigm defines the researcher’s philosophical orientation which has significant implications in the decision-making process of the research, including the questions of why, how and what to study. A paradigm is composed of four elements, namely ontology, epistemology, methodology and axiology (Lincoln and Guba, 2007; Kivunja and Kuyini, 2017). Ontology is the study of the nature of reality or being (Crotty, 1998). It examines the researcher’s underlying belief system regarding the nature of social phenomena they are investigating (Kivunja and Kuyini, 2017). Epistemology is concerned with the bases of human knowledge: its nature, form and how it can be acquired (Cohen et al., 2002). It focuses on the nature of knowledge the researcher can possibly acquire to extend, broaden and deepen their understanding of their chosen field of research (Kivunja and Kuyini, 2017). Methodology is basically the strategy or plan of action which lies behind the choice and use of particular methods chosen for the study (Crotty, 1998). Lastly, axiology, which is the philosophical approach for defining, evaluating and understanding concepts of right and wrong behaviour relating to the research (Finnis, 2011). In other words, it is concerned with the role of values and morals in social sciences (Bunge, 1996).

This discussion of the research paradigms validates Archer’s position because the researcher selects specific methods to investigate a certain problem based on what the researcher knows or assumes about the nature of the reality or truth they want to know and how knowledge about it can be acquired.
have already indicated that the recognition of multilevel structures and how these structures affect individual behaviour and action is the main premise of this thesis. The underlying assumption is that individual persons (women in this case) are nested across their communities and countries. Which means that their everyday life is not only influenced by their own individual agency alone but also their position relative to the social, cultural, economic and political structures of their community, country and the world at large. These hierarchical structures can either be manifest and easily quantifiable such as neighbourhoods, education levels, employment levels, level of economic development and health expenditure. Some other structures, however, may be latent and beneath the surface of observable phenomena (Scambler, 2001), but still holding potent power to influence individuals. These may include such abstractions as problematic gender norms, social exclusion, power inequalities and human rights violations. The modelling objective for this study includes these attributes because they contribute to our understanding of structural violence of the community and that of the nation state (Gultang, 1969). These structures may be experienced subjectively by individuals in different communities and countries. Moreover, if we are to explain structural violence, we should also research on how women may circumvent its influence in order in enhance their agency, and this brings in an aspect of emancipation to the process.

An appropriate ontological and epistemological foundation for the work of this nature must accommodate a complex and intertwined view of reality including both manifest and latent phenomena, morals and values and different geographical location. I argue that the positivist paradigm that has been dominant in quantitative social science for many years falls short in this score and may therefore, be problematic for the current study. I demonstrate this with reference to our four elements of the research paradigm (ontology, epistemology, methodology and axiology).

### The positivist paradigm

Ontologically, the positivist paradigm is aligned with objectivism. It is a philosophical position that social phenomena and their meaning exist independent of social actors (Bryman, 2016). It is a typical ontological position for the natural sciences to which positivism is associated because natural phenomena are generally rigid and unchangeable. This may be inappropriate ontological position for this study. I mainly look at the influence of structural characteristics on individual actors. These characteristics may exist outside individual consciousness and confront social actors as external realities, but they are not pre-given, and individuals do play a role in their (re)creation. I have shown in Chapter Three how it is possible for disadvantaged women to challenge existing problematic structural fundamentals both as individuals and as a collective conditional to having access to relevant resources (capital) enabling them to do so.

The other area where the positivist paradigm possesses some challenge for this study is on epistemology. The positivism uses empirical epistemology. Although there are different strands of positivism, they are all rooted in the philosophy of empiricism which posits that knowledge comes from sense-data inputs such as our ability to observe regularities (Giddens, 1995; Cruickshank, 2012). This makes positivism less compatible with analyses which seek to combine observable and non-observable data. It also tends to skew towards providing proof for causal directionality. That is, use of the scientific method would guarantee certainty in knowledge, with the outputs of science being an accurate reflection of reality (Cruickshank, 2012). Logical positivism on one hand for example defines science as an inductive method whereby the observation of an empirical regularity leads to the conclusion that one is observing a relation of cause and effect. It holds that the world consists of regularities that are detectable and thus the researcher can infer knowledge about the real world by just observing it (Giddens, 1995). The empirical positivism on the other hand is based on hypothetico-deductive logic and it argues for a more robust approach to science which goes beyond empirical observations to postulate an existence of unobservable causal law and then deduce from this law a prediction that an observable fixed pattern with occur in a particular manner. If one observes observable patterns as predicted then the hypothesis is corroborated, otherwise it is falsified or refuted. Therefore, in either form of positivism causal and effect assumptions are prominent and analytical statistics are used as tools to ground these causality assumptions (Cruickshank, 2012).

However, the position of positivism that statistical methods are tools which provide support for causal explanations as opposed to evidence of relationships or associations has been problematised in methodological literature (Porpora, 2001). Indeed, other than in some methods such as longitudinal studies, randomised clinical trials and experimental studies where some justification can be made for causal inference, quantitative methods are evidential rather than explanatory or causal tools. In most part, this study uses cross-sectional data which cannot be used to analyse cause and effect assumptions and as such analytical statistics are used here as tools to determine associations between concerned variables. Which makes it opposed to typical positivist assumptions.

In terms of methodology, positivists commit to a priori theorising and treats data as providing empirical verification of theoretical claims (Babones, 2013). The problem here is twofold. One has to do with the approach in terms of whether we should start from theory to data collection and the other, the philosophical justification of deriving evidence from theory. I am discussing the former here and the later will be discussed below. 

August Comte argued that theories were the bedrock of his methodological preferences of observation, experimentation and comparative methods. Indeed, in positivism researchers need to proceed from a theoretical standpoint. He indicated that theories direct our choice to pursue one fact rather than another (Giddens, 1995). Therefore, the positivist research process would typically begin with a theoretical formulation, followed by the deduction of hypotheses from the theories which are tested with data and are verified or falsified depending on whether one is using Comteian logical positivism or Popperian empirical positivism respectively (Babones, 2013). This approach is unattainable in studies like this one which are cross-national because it is almost impossible to draw new data for new studies. Which means it almost a given that cross-national researchers have to look at whether they have available data before considering any research questions.

Indeed, for this study, I began by having a cursory look at the available data and then created mechanisms of explanations by integrating a few Mertonian middle-range theories. There is nothing wrong with this approach either methodologically or theoretically, but it is certainly not positivism. Like Babones (2013) observes, the positivistic assumption of beginning with theory in cross-national and most observational studies seems disingenuous.
Additionally, positivist approaches tend to emphasise control into experimental and observational studies. For example, the control and experimental groups and the use of modelling techniques that tend to control for the influence of covariates. These are important techniques because they allow researchers to combine all factors and hence provide precision over inferences. The problem with this approach, however, is that it tends to severely restrict the ability to evaluate or measure contextual factors (Luke, 2004).

Axiologically, positivists believe that the researcher should be separated from the research process and that value judgements should be put at bay. I believe that how researchers deal with their value judgements throughout the research process from conceptualisation of the topic to data analysis is important. I recognise the controversy that may come with the inclusion of moral and value judgements in social research because of the ‘subjectivity’ connotation that comes with them, which scholars try to avoid in favour of ‘objective’ scientific inquiry. In fact, this point has been the main reason why certain topics that invoke normative moral judgements like human rights, structural violence and social justice have not been popular in the social sciences for a long time until now (Morgan, 2009). 

However, it is almost ubiquitous now in social science that normative neutrality is not constraining and that it may even be impossible to achieve because the whole research enterprise is engrained with unavoidable subjective choices (Morgan, 2009, Gill, 2014). Values shape the social behaviour of all members of society, social researchers included (Bunge, 1996). But of course, moral sensitivities to certain topics, should not be confused with lack of critical engagements with the subject matter. This is what the Germany sociologist Max Weber meant when he distinguished between the concepts of ‘value relevance’ and ‘value neutrality’ in sociology. In that, sociologists should allow themselves to be influenced by values at the point of subject selection, but to remain ‘value- free’ during the research process and in their pursuit of conclusions. I therefore, state from the outset that moral and value judgement played an important role in my choice to study structural violence and maternal healthcare utilisation in sub-Saharan Africa. I recognise that pregnancy and childbirth are not diseases, I do not believe any women deserves to die at any point throughout the maternal healthcare continuum. My desire to see a significant reduction in maternal mortality in the most affected regions of the world sparked my interest in this field and motivated me to pursue academic research in this field. Having said that, my discussion of the remaining parts of this chapter will be relative to the research paradigm of choice.

This consideration coupled with the others already explained drive this study away from a typical positivist paradigm. Social constructionism is a popular post-positivist ontological position which has as its foundation a recognition that the social world is inherently different from the material world and is a human social construction and is in a constant state of change (Bryman, 2016). It is based on a relativist philosophy and it holds that all knowledge is relative to one’s location within particular social norms and an interpretivist epistemology which emphasises the subjective meanings of social actions. Social research in this perspective is therefore a concerted effort of uncovering and interpreting the meanings underlying social phenomena. Qualitative research methods have largely been inspired by this orientation. Although they engage with theories the typical approach interpretive researchers informed studies is to understand the meanings attached to human actions. Theory may be the product and not the starting point. The use of quantitative methods and the cross-national nature of the current study makes the interpretivist approach inappropriate.

### Critical realism 

Considering the limitations of the other epistemological foundations, critical realism is argued to be most compatible for the current study for several reasons. Firstly, just like positivism and social constructivism, critical realism embodies theoretical assumptions about the nature of the natural and social worlds, and this determines the kind of methodology it employs. However, critical realism has the advantage of being able to incorporate important insights from other differing paradigms whilst bringing forward its own distinctive tenets (Porpora, 2001). For example, Roy Bhaskar, who is widely considered the founder of critical realism argued paralleling the hypothetico-deductive method of positivism, that unobservable causal laws interact in contingent ways to produce observable events (Bhaskar, 1975). However, unlike in positivism where observable events are seen to enlist certainty and concrete knowledge, critical realism holds that observable phenomena do not necessarily amount to certainty in knowledge. This is because the sphere of observable events was not permanent but subject to change overtime and also the theories which precede any empirical scientific investigation are still fallible interpretations that are subject to criticism and revision or replacement in the future (Cruickshank, 2012). Which means like Porpora (2001) posits, the truth that scientists hold is always provisional, and it must be allowed to be contested.

According to critical realism, what lies beneath observable events are unobservable social structures and the task of science, whether human, health or social is to employ theory to study and interpret how these social structures operated in an open system to produce different kinds of manifest patterns (Cruickshank, 2012). This study represents social structures as structural violence which in essence are constructed as having constraining powers inhibiting individual women to use maternal healthcare services which subsequently results into poor maternal health outcomes. These structures are social, economic, cultural and political in nature and operate at different levels. Accordingly, the study uses theories such as structural violence, capital theory and capabilities approach to interpret the manifestations of unobservable phenomena which in this case is structural violence.

Secondly, critical realism does not only accommodate latent structures as has been problematised above but also speaks to the negative enactments of structures to the extent that it is often referred to as the philosophy of emancipation (Porpora, 2015). Bhaskah, 2008 argued that the ‘critical’ part of critical realism represents the fact that in addition to applying knowledge positively, one may also use the knowledge to criticise any illegitimate practices. In this sense, critical realist-based studies can be used positively to develop policies against the marginalised and also as a way of criticising notions and practices that lead to such marginalisation with such criticisms based on an “objective” account (Cruickshank, 2012). It rejects the claims of value neutrality prominent in positivism. This standpoint is used in this study not only to expose structural mechanisms that constrain women from using maternal healthcare but also to advance policy frameworks aimed at minimising the negative influence of such structures.

Porpora (2001) holds that realism is humanism. He regards an individual as not only an agent but a moral one with experiencing and volitional characteristics. It recognises that structure can be enacted in a multiplicity of ways. For instance, although constraining, it can also be enabling and even motivational (Porpora, 2001). A recognition of individual agency makes critical realism all the more versatile and enables a holistic assessment of the position of individual actors in a constraining, enabling or motivational social system. This is the position this study takes. It investigates the constraining power of structure on individual actors while at the same time recognising individual abilities to determine their own course of action when certain resources are available.








